name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install packages
      run: yarn install --frozen-lockfile

    - name: Unit tests
      run: yarn test

    - name: Compile package
      run: yarn build
